version: "3"

# Restart param for production only

services:

  app:

      build: .

      volumes:
        - .:/app

      environment:
        - DRIVER_PATH=${DRIVER_PATH}

      # restart: always
